# Generated by Django 5.0 on 2023-12-30 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='id',
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
