# Generated by Django 5.0 on 2023-12-30 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_doctor_id_doctor_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specializasation',
            new_name='specialisation',
        ),
    ]
