# Generated by Django 5.0 on 2023-12-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_rename_specializasation_doctor_specialisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='Suhodolia', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Check review', 'Check review'), ('Planed treatment', 'Planed treatment'), ('Teeth cleaning', 'Teeth cleaning')], default='Check review', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('3 PM', '3 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7 PM'), ('7:30 PM', '7:30 PM'), ('9 AM', '9 AM'), ('9:30 AM', '9:30 AM'), ('10 AM', '10 AM'), ('11:30 AM', '11:30 AM'), ('12 AM', '12 AM'), ('13:30 AM', '13:30 AM'), ('14 AM', '14 AM'), ('15:30 AM', '15:30 AM')], default='3 PM', max_length=10),
        ),
    ]
